name: crypto_portfolio
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5

  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  equatable: ^2.0.5

  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
