name: crypto_portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'
dependencies: 
  bloc_concurrency: ^0.2.0
  dartz: ^0.10.1
  decimal: ^2.3.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_html: ^3.0.0-beta.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  money_formatter: ^0.0.3
  pie_chart: ^5.3.2
  pretty_dio_logger: ^1.2.0-beta-1
  rxdart: ^0.27.7
  syncfusion_flutter_charts: ^21.2.3
  url_launcher: ^6.1.10
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.12.0
  import_lint: ^1.0.0
  lints: ^2.0.1
  pubspec_dependency_sorter: ^1.0.3
flutter_icons: 
  android: launcher_icon
  image_path: assets/logo.png
  ios: true
  min_sdk_android: 21
flutter: 
  assets: 
    - assets/logo.png
  fonts: 
    - 
      family: AppIcons
      fonts: 
        - 
          asset: lib/application/app/design_system/icons/AppIcons.ttf
  uses-material-design: true
  generate: true
