name: crypto_portfolio
version: 1.0.1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #dart.dev
  intl: ^0.18.0

  #google.dev
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  #flutter.dev
  url_launcher: ^6.1.12
  path_provider: ^2.1.0
  shared_preferences: ^2.2.2

  #fluttercommunity.dev
  rxdart: ^0.27.7
  equatable: ^2.0.5

  #flutter.cn
  dio: ^5.3.2

  #dash-overflow.net
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1

  #bloclibrary.dev
  bloc_concurrency: ^0.2.2
  flutter_bloc: ^8.1.3

  #syncfusion.com
  syncfusion_flutter_charts: ^22.2.7

  #sub6resources.com
  flutter_html: ^3.0.0-beta.2

  #isar.dev
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14

  #wiseminds.cc
  money_formatter: ^0.0.4

  #tekartik.com
  synchronized: ^3.1.0

  #ayushpgupta.com
  pie_chart: ^5.3.2

  dartz: ^0.10.1
  decimal: ^2.3.2

dev_dependencies:

  #tools.dart.dev
  build_runner: ^2.4.6
  lints: ^2.1.1

  #fluttercommunity.dev
  flutter_launcher_icons: ^0.12.0

flutter_icons: 
  android: launcher_icon
  image_path: assets/app/logo.png
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/app/logo.png
    - assets/news_instruction/tap_header.png
    - assets/news_instruction/tap_source.png
  fonts: 
    - 
      family: AppIcons
      fonts: 
        - 
          asset: lib/common/assets/icons/AppIcons.ttf
  uses-material-design: true
  generate: true
