name: crypto_portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'
dependencies: 
  bloc_concurrency: ^0.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  money_formatter: ^0.0.3
  pretty_dio_logger: ^1.2.0-beta-1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.3.2
  import_lint: ^0.9.4
  lints: ^2.0.1
  pubspec_dependency_sorter: ^1.0.3
flutter: 
  uses-material-design: true
  generate: true
